### ISSUE TITLE
Build fails because of unused imports

### ISSUE THREAD

**Issue by kevinearls** [Hawkular-QE/hawkular-apm-qe#1]
mvn clean install with the following checkstyle violations:

<file name="/Volumes/Samsung_T1/sources/hawkular-qe/forks/hawkular-apm-qe/src/test/java/org/hawkular/apm/qe/tests/MyTestNG.java">
<error line="19" column="8" severity="error" message="Unused import - org.hawkular.apm.api.model.trace.Trace." source="com.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck"/>
<error line="20" column="8" severity="error" message="Unused import - org.hawkular.client.core.ClientResponse." source="com.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck"/>
<error line="21" column="8" severity="error" message="Unused import - org.testng.Assert." source="com.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck"/>
</file>

**Comment by jkandasa** [comment]
was close on https://github.com/Hawkular-QE/hawkular-apm-qe/pull/3

Thanks @kevinearls
